# Generated by Django 3.2.25 on 2024-05-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='kind',
            field=models.IntegerField(choices=[('单选题', 1), ('多选题', 2), ('应用题', 3)]),
        ),
    ]
