# Generated by Django 3.2.25 on 2024-05-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usage',
            options={},
        ),
        migrations.AlterField(
            model_name='language',
            name='expression',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='word',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usage',
            name='example',
            field=models.CharField(max_length=100),
        ),
    ]
