# Generated by Django 3.2.25 on 2024-05-13 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argumentation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='content',
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argumentation.reading')),
            ],
        ),
    ]
