# Generated by Django 3.2.25 on 2024-05-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argumentation', '0002_auto_20240513_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='no',
            field=models.IntegerField(default=0),
        ),
    ]
