# Generated by Django 3.2.25 on 2024-05-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argumentation', '0003_paragraph_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='required',
            field=models.IntegerField(default=0),
        ),
    ]
