# Generated by Django 4.0.1 on 2022-08-18 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='最后更新时间')),
                ('created', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='创建时间')),
                ('title', models.CharField(default=datetime.date(2022, 8, 18), max_length=50, unique=True, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name_plural': '千纸鹤写作',
                'db_table': 'post',
            },
        ),
    ]
