# Generated by Django 4.0.1 on 2022-08-26 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='最后更新时间')),
                ('created', models.DateField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('uid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name_plural': '千纸鹤写作',
                'db_table': 'post',
            },
        ),
    ]
